"""What each automation trigger puts in `trigger_data`, for the field picker.

The builder may only offer a variable that resolves at execution time. An
unknown path is not cosmetic: the canvas/Temporal executor fails the step with
"Dynamic value '{{...}}' is missing", and the inline executor renders the
literal braces into the email or webhook body.

So none of this is hand-authored from the trigger names. Every key below was
read off the service that dispatches that event — CRMEventService, the CRM
schedule runner, and the ~80 dispatch_automation_event call sites across
ticket_service, hiring, campaign_service, uptime_service, the sprint services,
form_submission_handler, booking, tracking_events and compliance_service.

Entries are ``(path, label, type, description)``. Dict-valued payload keys
(values, changes, field_values, data, answers, …) can be drilled into —
``{{trigger.new_values.email}}`` resolves, because both resolvers walk nested
dicts.
"""

# Trigger payload keys the builder's field picker may offer, per CRM trigger.
#
# Each entry was read off the service that dispatches that event —
# CRMEventService in services/crm_events.py, and the schedule runner in
# temporal/activities/crm_automation_schedule.py — because the picker's job is
# to offer paths that resolve. The previous list was hand-written and mostly
# did not: it advertised trigger.triggered_by and trigger.triggered_at for
# every trigger (no emitter sets either) and trigger.field_slug for
# field.changed (the key is changed_field), so picking any of them produced a
# step that failed at run time.
#
# Dict-valued entries (values, changes, data, …) can be drilled into —
# {{trigger.new_values.email}} resolves, since both resolvers walk nested dicts.
_CRM_EVENT_FIELDS: tuple[tuple[str, str, str, str], ...] = (
    ("trigger.trigger_type", "Trigger Type", "text", "The event that started this run"),
    ("trigger.workspace_id", "Workspace ID", "text", "ID of the workspace"),
    ("trigger.object_id", "Object Type ID", "text", "CRM object the record belongs to"),
    ("trigger.record_id", "Record ID", "text", "ID of the triggering record"),
)

_SCHEDULE_FIELDS: tuple[tuple[str, str, str, str], ...] = (
    ("trigger.trigger_type", "Trigger Type", "text", "The event that started this run"),
    ("trigger.scheduled", "Scheduled Run", "boolean", "Always true for schedule-driven runs"),
    ("trigger.fired_at", "Fired At", "timestamp", "When the schedule runner fired (ISO 8601)"),
)

_CRM_TRIGGER_FIELDS: dict[str, tuple[tuple[str, str, str, str], ...]] = {
    "record.created": _CRM_EVENT_FIELDS + (
        ("trigger.values", "Record Values", "object", "Field values at creation — drill in with trigger.values.<field_slug>"),
        ("trigger.created_by_id", "Created By", "text", "ID of the user who created the record"),
    ),
    "record.updated": _CRM_EVENT_FIELDS + (
        ("trigger.old_values", "Previous Values", "object", "Field values before the update"),
        ("trigger.new_values", "New Values", "object", "Field values after the update"),
        ("trigger.changes", "Changes", "object", "Only the fields that changed"),
        ("trigger.updated_by_id", "Updated By", "text", "ID of the user who updated the record"),
    ),
    "record.deleted": _CRM_EVENT_FIELDS + (
        ("trigger.values", "Record Values", "object", "Field values at deletion"),
        ("trigger.permanent", "Permanent Delete", "boolean", "True for a hard delete, false for archive"),
        ("trigger.deleted_by_id", "Deleted By", "text", "ID of the user who deleted the record"),
    ),
    "field.changed": _CRM_EVENT_FIELDS + (
        ("trigger.changed_field", "Changed Field", "text", "Slug of the field that changed"),
        ("trigger.old_value", "Old Value", "text", "Value before the change"),
        ("trigger.new_value", "New Value", "text", "Value after the change"),
        ("trigger.old_values", "Previous Values", "object", "All field values before the update"),
        ("trigger.new_values", "New Values", "object", "All field values after the update"),
        ("trigger.changes", "Changes", "object", "Every field that changed in this update"),
        ("trigger.updated_by_id", "Updated By", "text", "ID of the user who updated the record"),
    ),
    "stage.changed": _CRM_EVENT_FIELDS + (
        ("trigger.old_stage", "Previous Stage", "text", "Stage the record moved out of"),
        ("trigger.new_stage", "New Stage", "text", "Stage the record moved into"),
        ("trigger.changed_by_id", "Changed By", "text", "ID of the user who moved the record"),
    ),
    "list_entry.added": _CRM_EVENT_FIELDS + (
        ("trigger.list_id", "List ID", "text", "ID of the list"),
        ("trigger.list_name", "List Name", "text", "Name of the list"),
        ("trigger.added_by_id", "Added By", "text", "ID of the user who added the record"),
    ),
    "list_entry.removed": _CRM_EVENT_FIELDS + (
        ("trigger.list_id", "List ID", "text", "ID of the list"),
        ("trigger.list_name", "List Name", "text", "Name of the list"),
        ("trigger.removed_by_id", "Removed By", "text", "ID of the user who removed the record"),
    ),
    "form.submitted": _CRM_EVENT_FIELDS + (
        ("trigger.form_id", "Form ID", "text", "ID of the submitted form"),
        ("trigger.form_name", "Form Name", "text", "Name of the submitted form"),
        ("trigger.submission_id", "Submission ID", "text", "ID of this submission"),
        ("trigger.data", "Submission Data", "object", "Submitted answers — drill in with trigger.data.<field>"),
    ),
    "email.opened": _CRM_EVENT_FIELDS + (
        ("trigger.campaign_id", "Campaign ID", "text", "Campaign the email belongs to"),
        ("trigger.pixel_id", "Tracking Pixel ID", "text", "ID of the tracking pixel that fired"),
    ),
    "email.clicked": _CRM_EVENT_FIELDS + (
        ("trigger.url", "Clicked URL", "url", "URL of the clicked link"),
        ("trigger.campaign_id", "Campaign ID", "text", "Campaign the email belongs to"),
        ("trigger.link_id", "Link ID", "text", "ID of the tracked link"),
    ),
    "schedule.daily": _SCHEDULE_FIELDS,
    "schedule.weekly": _SCHEDULE_FIELDS,
    "date.approaching": _SCHEDULE_FIELDS + (
        ("trigger.attribute_slug", "Date Field", "text", "Slug of the date field being watched"),
        ("trigger.date_value", "Date Value", "text", "Value of the watched date field"),
        ("trigger.days_until", "Days Until", "number", "Days between now and the date"),
    ),
    "date.passed": _SCHEDULE_FIELDS + (
        ("trigger.attribute_slug", "Date Field", "text", "Slug of the date field being watched"),
        ("trigger.date_value", "Date Value", "text", "Value of the watched date field"),
        ("trigger.days_until", "Days Until", "number", "Days since the date (negative)"),
    ),
}


_SERVICE_DESK_TICKET_FIELDS: tuple[tuple[str, str, str, str], ...] = (
    ("trigger.ticket_id", "Ticket ID", "text", ""),
    ("trigger.ticket_number", "Ticket Number", "number", ""),
    ("trigger.title", "Title", "text", ""),
    ("trigger.status", "Status", "text", ""),
    ("trigger.priority", "Priority", "text", ""),
    ("trigger.request_type", "Request Type", "text", ""),
    ("trigger.pending_with", "Pending With", "text", "Stakeholder the ticket is parked with"),
    ("trigger.account_id", "Account ID", "text", ""),
    ("trigger.assigned_owner_id", "Assigned Owner ID", "text", ""),
    ("trigger.source", "Source", "text", "email, manual, api"),
    ("trigger.needs_triage", "Needs Triage", "boolean", "AI could not classify it confidently"),
    ("trigger.workspace_id", "Workspace ID", "text", ""),
)


_MODULE_TRIGGER_FIELDS: dict[str, dict[str, tuple[tuple[str, str, str, str], ...]]] = {
    "booking": {
        "booking.cancelled": (
            ("trigger.cancellation_reason", "Cancellation Reason", "text", ""),
            ("trigger.cancelled_by", "Cancelled By", "text", ""),
            ("trigger.email", "Email", "email", ""),
            ("trigger.end_time", "End Time", "timestamp", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.start_time", "Start Time", "timestamp", ""),
            ("trigger.status", "Status", "text", ""),
        ),
        "booking.completed": (
            ("trigger.email", "Email", "email", ""),
            ("trigger.end_time", "End Time", "timestamp", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.start_time", "Start Time", "timestamp", ""),
            ("trigger.status", "Status", "text", ""),
        ),
        "booking.confirmed": (
            ("trigger.email", "Email", "email", ""),
            ("trigger.end_time", "End Time", "timestamp", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.start_time", "Start Time", "timestamp", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.timezone", "Timezone", "text", ""),
        ),
        "booking.created": (
            ("trigger.answers", "Answers", "object", ""),
            ("trigger.email", "Email", "email", ""),
            ("trigger.end_time", "End Time", "timestamp", ""),
            ("trigger.event_type_id", "Event Type ID", "text", ""),
            ("trigger.host_id", "Host ID", "text", ""),
            ("trigger.location", "Location", "text", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.phone", "Phone", "text", ""),
            ("trigger.start_time", "Start Time", "timestamp", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.timezone", "Timezone", "text", ""),
        ),
        "booking.no_show": (
            ("trigger.email", "Email", "email", ""),
            ("trigger.end_time", "End Time", "timestamp", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.start_time", "Start Time", "timestamp", ""),
            ("trigger.status", "Status", "text", ""),
        ),
        "booking.reminder": (
            ("trigger.email", "Email", "email", ""),
            ("trigger.end_time", "End Time", "timestamp", ""),
            ("trigger.hours_before", "Hours Before", "number", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.start_time", "Start Time", "timestamp", ""),
        ),
        "booking.rescheduled": (
            ("trigger.email", "Email", "email", ""),
            ("trigger.end_time", "End Time", "timestamp", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.start_time", "Start Time", "timestamp", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.timezone", "Timezone", "text", ""),
        ),
    },
    "compliance": {
        "assignment.approaching_due": (
            ("trigger.assignment_id", "Assignment ID", "text", ""),
            ("trigger.days_until_due", "Days Until Due", "number", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.due_date", "Due Date", "timestamp", ""),
            ("trigger.training_id", "Training ID", "text", ""),
        ),
        "assignment.overdue": (
            ("trigger.assignment_id", "Assignment ID", "text", ""),
            ("trigger.days_overdue", "Days Overdue", "number", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.due_date", "Due Date", "timestamp", ""),
            ("trigger.training_id", "Training ID", "text", ""),
        ),
        "audit.logged": (
            ("trigger.action_type", "Action Type", "text", ""),
            ("trigger.actor_id", "Actor ID", "text", ""),
            ("trigger.description", "Description", "text", ""),
            ("trigger.target_id", "Target ID", "text", ""),
            ("trigger.target_type", "Target Type", "text", ""),
        ),
        "certification.added": (
            ("trigger.certification_id", "Certification ID", "text", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.expiry_date", "Expiry Date", "timestamp", ""),
            ("trigger.issued_date", "Issued Date", "timestamp", ""),
        ),
        "certification.expired": (
            ("trigger.certification_id", "Certification ID", "text", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.expiry_date", "Expiry Date", "timestamp", ""),
        ),
        "certification.expiring": (
            ("trigger.certification_id", "Certification ID", "text", ""),
            ("trigger.days_until_expiry", "Days Until Expiry", "number", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.expiry_date", "Expiry Date", "timestamp", ""),
        ),
        "certification.prerequisite_unmet": (
            ("trigger.certification_id", "Certification ID", "text", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.missing_prerequisites", "Missing Prerequisites", "object", ""),
        ),
        "certification.renewed": (
            ("trigger.certification_id", "Certification ID", "text", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.new_expiry_date", "New Expiry Date", "timestamp", ""),
        ),
        "certification.revoked": (
            ("trigger.certification_id", "Certification ID", "text", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.revoked_by_id", "Revoked By ID", "text", ""),
        ),
        "compliance.status_changed": (
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.is_compliant", "Is Compliant", "boolean", ""),
            ("trigger.was_compliant", "Was Compliant", "boolean", ""),
        ),
        "training.assigned": (
            ("trigger.assignment_id", "Assignment ID", "text", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.due_date", "Due Date", "timestamp", ""),
            ("trigger.training_id", "Training ID", "text", ""),
        ),
        "training.bulk_overdue": (
            ("trigger.overdue_assignments", "Overdue Assignments", "number", ""),
            ("trigger.overdue_rate", "Overdue Rate", "number", ""),
            ("trigger.team_id", "Team ID", "text", ""),
            ("trigger.team_name", "Team Name", "text", ""),
            ("trigger.threshold", "Threshold", "number", ""),
            ("trigger.total_assignments", "Total Assignments", "number", ""),
        ),
        "training.completed": (
            ("trigger.assignment_id", "Assignment ID", "text", ""),
            ("trigger.completed_at", "Completed At", "timestamp", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.training_id", "Training ID", "text", ""),
        ),
        "training.created": (
            ("trigger.applies_to_type", "Applies To Type", "text", ""),
            ("trigger.due_days", "Due Days", "number", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.training_id", "Training ID", "text", ""),
        ),
        "training.started": (
            ("trigger.assignment_id", "Assignment ID", "text", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.training_id", "Training ID", "text", ""),
        ),
        "training.waived": (
            ("trigger.assignment_id", "Assignment ID", "text", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.waived_by_id", "Waived By ID", "text", ""),
            ("trigger.waiver_reason", "Waiver Reason", "text", ""),
        ),
    },
    "email_marketing": {
        "campaign.scheduled": (
            ("trigger.campaign_id", "Campaign ID", "text", ""),
            ("trigger.campaign_name", "Campaign Name", "text", ""),
            ("trigger.scheduled_at", "Scheduled At", "timestamp", ""),
            ("trigger.total_recipients", "Total Recipients", "number", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "campaign.sent": (
            ("trigger.campaign_name", "Campaign Name", "text", ""),
            ("trigger.completed_at", "Completed At", "timestamp", ""),
            ("trigger.total_recipients", "Total Recipients", "number", ""),
        ),
        "email.clicked": (
            ("trigger.campaign_id", "Campaign ID", "text", ""),
            ("trigger.link_id", "Link ID", "text", ""),
            ("trigger.original_url", "Original URL", "url", ""),
            ("trigger.recipient_id", "Recipient ID", "text", ""),
        ),
        "email.opened": (
            ("trigger.campaign_id", "Campaign ID", "text", ""),
            ("trigger.pixel_id", "Pixel ID", "text", ""),
            ("trigger.recipient_id", "Recipient ID", "text", ""),
        ),
        "email.unsubscribed": (
            ("trigger.campaign_id", "Campaign ID", "text", ""),
            ("trigger.subscriber_email", "Subscriber Email", "email", ""),
        ),
        "recipient.added": (
            ("trigger.campaign_id", "Campaign ID", "text", ""),
            ("trigger.campaign_name", "Campaign Name", "text", ""),
            ("trigger.recipients_added", "Recipients Added", "number", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
    },
    "forms": {
        "form.submitted": (
            ("trigger.crm_record_id", "Crm Record ID", "text", ""),
            ("trigger.data", "Data", "object", ""),
            ("trigger.deal_id", "Deal ID", "text", ""),
            ("trigger.email", "Email", "email", ""),
            ("trigger.form_id", "Form ID", "text", ""),
            ("trigger.form_name", "Form Name", "text", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.submission_id", "Submission ID", "text", ""),
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
    },
    "hiring": {
        "assessment.completed": (
            ("trigger.assessment_id", "Assessment ID", "text", ""),
            ("trigger.assessment_title", "Assessment Title", "text", ""),
            ("trigger.attempt_id", "Attempt ID", "text", ""),
            ("trigger.candidate_email", "Candidate Email", "email", ""),
            ("trigger.candidate_id", "Candidate ID", "text", ""),
            ("trigger.candidate_name", "Candidate Name", "text", ""),
            ("trigger.completed_at", "Completed At", "timestamp", ""),
            ("trigger.max_score", "Max Score", "number", ""),
            ("trigger.percentage_score", "Percentage Score", "number", ""),
            ("trigger.total_score", "Total Score", "number", ""),
            ("trigger.trust_level", "Trust Level", "number", ""),
            ("trigger.trust_score", "Trust Score", "number", ""),
        ),
        "assessment.score_above": (
            ("trigger.assessment_id", "Assessment ID", "text", ""),
            ("trigger.assessment_title", "Assessment Title", "text", ""),
            ("trigger.attempt_id", "Attempt ID", "text", ""),
            ("trigger.candidate_email", "Candidate Email", "email", ""),
            ("trigger.candidate_name", "Candidate Name", "text", ""),
            ("trigger.percentage_score", "Percentage Score", "number", ""),
            ("trigger.threshold", "Threshold", "number", ""),
        ),
        "assessment.score_below": (
            ("trigger.assessment_id", "Assessment ID", "text", ""),
            ("trigger.assessment_title", "Assessment Title", "text", ""),
            ("trigger.attempt_id", "Attempt ID", "text", ""),
            ("trigger.candidate_email", "Candidate Email", "email", ""),
            ("trigger.candidate_name", "Candidate Name", "text", ""),
            ("trigger.percentage_score", "Percentage Score", "number", ""),
            ("trigger.threshold", "Threshold", "number", ""),
        ),
        "candidate.created": (
            ("trigger.current_company", "Current Company", "text", ""),
            ("trigger.email", "Email", "email", ""),
            ("trigger.experience_years", "Experience Years", "number", ""),
            ("trigger.location", "Location", "text", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.role", "Role", "text", ""),
            ("trigger.score", "Score", "number", ""),
            ("trigger.source", "Source", "text", ""),
            ("trigger.stage", "Stage", "text", ""),
        ),
        "candidate.hired": (
            ("trigger.email", "Email", "email", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.old_stage", "Old Stage", "text", ""),
            ("trigger.role", "Role", "text", ""),
            ("trigger.score", "Score", "number", ""),
        ),
        "candidate.rejected": (
            ("trigger.email", "Email", "email", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.old_stage", "Old Stage", "text", ""),
            ("trigger.role", "Role", "text", ""),
            ("trigger.score", "Score", "number", ""),
        ),
        "candidate.stage_changed": (
            ("trigger.email", "Email", "email", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.new_stage", "New Stage", "text", ""),
            ("trigger.old_stage", "Old Stage", "text", ""),
            ("trigger.role", "Role", "text", ""),
            ("trigger.score", "Score", "number", ""),
        ),
        "candidate.updated": (
            ("trigger.email", "Email", "email", ""),
            ("trigger.location", "Location", "text", ""),
            ("trigger.name", "Name", "text", ""),
            ("trigger.role", "Role", "text", ""),
            ("trigger.score", "Score", "number", ""),
            ("trigger.source", "Source", "text", ""),
            ("trigger.stage", "Stage", "text", ""),
            ("trigger.updated_fields", "Updated Fields", "object", ""),
        ),
        "requirement.created": (
            ("trigger.must_have_skills", "Must Have Skills", "object", ""),
            ("trigger.nice_to_have_skills", "Nice To Have Skills", "object", ""),
            ("trigger.priority", "Priority", "text", ""),
            ("trigger.role_title", "Role Title", "text", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.team_id", "Team ID", "text", ""),
            ("trigger.timeline", "Timeline", "text", ""),
        ),
        "requirement.status_changed": (
            ("trigger.new_status", "New Status", "text", ""),
            ("trigger.old_status", "Old Status", "text", ""),
            ("trigger.priority", "Priority", "text", ""),
            ("trigger.role_title", "Role Title", "text", ""),
        ),
    },
    "sprints": {
        "epic.completed": (
            ("trigger.completed_tasks", "Completed Tasks", "number", ""),
            ("trigger.epic_title", "Epic Title", "text", ""),
            ("trigger.total_story_points", "Total Story Points", "number", ""),
            ("trigger.total_tasks", "Total Tasks", "number", ""),
        ),
        "sprint.burndown_off_track": (
            ("trigger.actual_remaining", "Actual Remaining", "number", ""),
            ("trigger.completed_points", "Completed Points", "number", ""),
            ("trigger.deviation_pct", "Deviation %", "number", ""),
            ("trigger.ideal_remaining", "Ideal Remaining", "number", ""),
            ("trigger.snapshot_date", "Snapshot Date", "timestamp", ""),
            ("trigger.sprint_name", "Sprint Name", "text", ""),
            ("trigger.team_id", "Team ID", "text", ""),
            ("trigger.total_points", "Total Points", "number", ""),
        ),
        "sprint.completed": (
            ("trigger.sprint_name", "Sprint Name", "text", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.team_id", "Team ID", "text", ""),
        ),
        "sprint.started": (
            ("trigger.sprint_name", "Sprint Name", "text", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.team_id", "Team ID", "text", ""),
        ),
        "sprint.velocity_calculated": (
            ("trigger.carry_over_points", "Carry Over Points", "number", ""),
            ("trigger.committed_points", "Committed Points", "number", ""),
            ("trigger.completed_points", "Completed Points", "number", ""),
            ("trigger.completion_rate", "Completion Rate", "number", ""),
            ("trigger.focus_factor", "Focus Factor", "number", ""),
            ("trigger.sprint_name", "Sprint Name", "text", ""),
            ("trigger.team_id", "Team ID", "text", ""),
        ),
        "task.assigned": (
            ("trigger.assignee_email", "Assignee Email", "email", ""),
            ("trigger.assignee_id", "Assignee ID", "text", ""),
            ("trigger.assignment_reason", "Assignment Reason", "text", ""),
            ("trigger.sprint_id", "Sprint ID", "text", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.task_id", "Task ID", "text", ""),
            ("trigger.task_title", "Task Title", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "task.completed": (
            ("trigger.task_id", "Task ID", "text", ""),
            ("trigger.task_title", "Task Title", "text", ""),
            ("trigger.sprint_id", "Sprint ID", "text", ""),
            ("trigger.old_status", "Old Status", "text", ""),
            ("trigger.new_status", "New Status", "text", ""),
            ("trigger.assignee_id", "Assignee ID", "text", ""),
            ("trigger.assignee_email", "Assignee Email", "email", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "task.created": (
            ("trigger.assignee_email", "Assignee Email", "email", ""),
            ("trigger.assignee_id", "Assignee ID", "text", ""),
            ("trigger.epic_id", "Epic ID", "text", ""),
            ("trigger.priority", "Priority", "text", ""),
            ("trigger.project_id", "Project ID", "text", ""),
            ("trigger.sprint_id", "Sprint ID", "text", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.story_points", "Story Points", "number", ""),
            ("trigger.task_id", "Task ID", "text", ""),
            ("trigger.task_title", "Task Title", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "task.status_changed": (
            ("trigger.task_id", "Task ID", "text", ""),
            ("trigger.task_title", "Task Title", "text", ""),
            ("trigger.sprint_id", "Sprint ID", "text", ""),
            ("trigger.old_status", "Old Status", "text", ""),
            ("trigger.new_status", "New Status", "text", ""),
            ("trigger.assignee_id", "Assignee ID", "text", ""),
            ("trigger.assignee_email", "Assignee Email", "email", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
    },
    "service_desk": {
        "service_desk.ticket_created": _SERVICE_DESK_TICKET_FIELDS,
        "service_desk.ticket_updated": _SERVICE_DESK_TICKET_FIELDS + (
            ("trigger.changed_fields", "Changed Fields", "object", "Field name to new value"),
        ),
        "service_desk.pending_with_changed": _SERVICE_DESK_TICKET_FIELDS + (
            ("trigger.previous_pending_with", "Previous Pending With", "text", ""),
            ("trigger.note", "Note", "text", "The note left with the change, if any"),
        ),
    },
    "tickets": {
        "alert.ticket_created": (
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "number", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.priority", "Priority", "text", ""),
            ("trigger.severity", "Severity", "text", ""),
            ("trigger.source", "Source", "text", ""),
            ("trigger.service", "Service", "text", "Service the alert came from"),
            ("trigger.alert_name", "Alert Name", "text", ""),
            ("trigger.occurrence_count", "Occurrence Count", "number", "How many times this alert has fired"),
            ("trigger.dedup_key", "Dedup Key", "text", ""),
            ("trigger.field_values", "Field Values", "object", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "alert.ticket_updated": (
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "number", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.priority", "Priority", "text", ""),
            ("trigger.severity", "Severity", "text", ""),
            ("trigger.source", "Source", "text", ""),
            ("trigger.service", "Service", "text", "Service the alert came from"),
            ("trigger.alert_name", "Alert Name", "text", ""),
            ("trigger.occurrence_count", "Occurrence Count", "number", "How many times this alert has fired"),
            ("trigger.dedup_key", "Dedup Key", "text", ""),
            ("trigger.field_values", "Field Values", "object", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "response.received": (
            ("trigger.author_email", "Author Email", "email", ""),
            ("trigger.response_id", "Response ID", "text", ""),
            ("trigger.submitter_email", "Submitter Email", "email", ""),
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "response.sent": (
            ("trigger.author_id", "Author ID", "text", ""),
            ("trigger.response_id", "Response ID", "text", ""),
            ("trigger.submitter_email", "Submitter Email", "email", ""),
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "sla.breached": (
            ("trigger.assignee_id", "Assignee ID", "text", ""),
            ("trigger.priority", "Priority", "text", ""),
            ("trigger.sla_due_at", "SLA Due At", "timestamp", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.submitter_email", "Submitter Email", "email", ""),
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "ticket.assigned": (
            ("trigger.assigned_by_id", "Assigned By ID", "text", ""),
            ("trigger.assignee_id", "Assignee ID", "text", ""),
            ("trigger.old_assignee_id", "Old Assignee ID", "text", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.submitter_email", "Submitter Email", "email", ""),
            ("trigger.team_id", "Team ID", "text", ""),
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "ticket.created": (
            ("trigger.field_values", "Field Values", "object", ""),
            ("trigger.form_id", "Form ID", "text", ""),
            ("trigger.priority", "Priority", "text", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.submitter_email", "Submitter Email", "email", ""),
            ("trigger.submitter_name", "Submitter Name", "text", ""),
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "ticket.escalated": (
            ("trigger.escalation_id", "Escalation ID", "text", ""),
            ("trigger.escalation_level", "Escalation Level", "number", ""),
            ("trigger.notified_users", "Notified Users", "object", ""),
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "ticket.priority_changed": (
            ("trigger.new_priority", "New Priority", "text", ""),
            ("trigger.old_priority", "Old Priority", "text", ""),
            ("trigger.submitter_email", "Submitter Email", "email", ""),
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "ticket.reopened": (
            ("trigger.assignee_id", "Assignee ID", "text", ""),
            ("trigger.new_status", "New Status", "text", ""),
            ("trigger.old_status", "Old Status", "text", ""),
            ("trigger.reopened_by_id", "Reopened By ID", "text", ""),
            ("trigger.submitter_email", "Submitter Email", "email", ""),
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "ticket.status_changed": (
            ("trigger.assignee_id", "Assignee ID", "text", ""),
            ("trigger.new_status", "New Status", "text", ""),
            ("trigger.old_status", "Old Status", "text", ""),
            ("trigger.submitter_email", "Submitter Email", "email", ""),
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
        "ticket.updated": (
            ("trigger.priority", "Priority", "text", ""),
            ("trigger.status", "Status", "text", ""),
            ("trigger.submitter_email", "Submitter Email", "email", ""),
            ("trigger.ticket_id", "Ticket ID", "text", ""),
            ("trigger.ticket_number", "Ticket Number", "text", ""),
            ("trigger.updated_fields", "Updated Fields", "object", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
        ),
    },
    "tracking": {
        "blocker.created": (
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.team_id", "Team ID", "text", ""),
            ("trigger.task_id", "Task ID", "text", ""),
            ("trigger.description", "Description", "text", ""),
            ("trigger.severity", "Severity", "text", ""),
        ),
        "blocker.escalated": (
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.description", "Description", "text", ""),
            ("trigger.severity", "Severity", "text", ""),
            ("trigger.escalated_to_id", "Escalated To ID", "text", ""),
        ),
        "blocker.pattern_detected": (
            ("trigger.category", "Category", "text", ""),
            ("trigger.count", "Count", "number", ""),
            ("trigger.period_days", "Period Days", "number", ""),
            ("trigger.team_id", "Team ID", "text", ""),
        ),
        "blocker.resolved": (
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.resolved_by_id", "Resolved By ID", "text", ""),
            ("trigger.time_to_resolve_hours", "Time To Resolve Hours", "number", ""),
        ),
        "blocker.stale": (
            ("trigger.days_stale", "Days Stale", "number", ""),
            ("trigger.description", "Description", "text", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.severity", "Severity", "text", ""),
            ("trigger.team_id", "Team ID", "text", ""),
        ),
        "participation.low": (
            ("trigger.participation_rate", "Participation Rate", "number", ""),
            ("trigger.submitted", "Submitted", "number", ""),
            ("trigger.team_id", "Team ID", "text", ""),
            ("trigger.team_name", "Team Name", "text", ""),
            ("trigger.threshold", "Threshold", "number", ""),
            ("trigger.total_members", "Total Members", "number", ""),
        ),
        "sentiment.negative": (
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.team_id", "Team ID", "text", ""),
            ("trigger.sentiment_score", "Sentiment Score", "number", ""),
            ("trigger.concerns", "Concerns", "object", ""),
        ),
        "standup.missed": (
            ("trigger.date", "Date", "timestamp", ""),
            ("trigger.deadline_hour", "Deadline Hour", "number", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.team_id", "Team ID", "text", ""),
        ),
        "standup.streak": (
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.team_id", "Team ID", "text", ""),
            ("trigger.streak_count", "Streak Count", "number", ""),
            ("trigger.milestone", "Milestone", "text", ""),
        ),
        "standup.submitted": (
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.team_id", "Team ID", "text", ""),
            ("trigger.standup_date", "Standup Date", "timestamp", ""),
            ("trigger.yesterday_summary", "Yesterday Summary", "text", ""),
            ("trigger.today_plan", "Today Plan", "text", ""),
            ("trigger.blockers_summary", "Blockers Summary", "text", ""),
        ),
        "time_entry.anomaly": (
            ("trigger.anomaly_type", "Anomaly Type", "text", ""),
            ("trigger.date", "Date", "timestamp", ""),
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.total_minutes", "Total Minutes", "number", ""),
        ),
        "time_entry.created": (
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.task_id", "Task ID", "text", ""),
            ("trigger.duration_minutes", "Duration Minutes", "number", ""),
            ("trigger.entry_date", "Entry Date", "timestamp", ""),
            ("trigger.source", "Source", "text", ""),
        ),
        "time_entry.threshold": (
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.direction", "Direction", "text", ""),
            ("trigger.period", "Period", "text", ""),
            ("trigger.threshold_minutes", "Threshold Minutes", "number", ""),
            ("trigger.total_minutes", "Total Minutes", "number", ""),
        ),
        "work_log.submitted": (
            ("trigger.developer_id", "Developer ID", "text", ""),
            ("trigger.task_id", "Task ID", "text", ""),
            ("trigger.log_type", "Log Type", "text", ""),
            ("trigger.notes", "Notes", "text", ""),
        ),
    },
    "uptime": {
        "incident.acknowledged": (
            ("trigger.monitor_id", "Monitor ID", "text", ""),
            ("trigger.monitor_name", "Monitor Name", "text", ""),
            ("trigger.check_type", "Check Type", "text", ""),
            ("trigger.url", "URL", "url", ""),
            ("trigger.host", "Host", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
            ("trigger.response_time_ms", "Response Time (ms)", "number", ""),
            ("trigger.error_message", "Error Message", "text", ""),
            ("trigger.acknowledged_at", "Acknowledged At", "timestamp", ""),
            ("trigger.acknowledged_by_id", "Acknowledged By ID", "text", ""),
            ("trigger.incident_id", "Incident ID", "text", ""),
        ),
        "incident.created": (
            ("trigger.monitor_id", "Monitor ID", "text", ""),
            ("trigger.monitor_name", "Monitor Name", "text", ""),
            ("trigger.check_type", "Check Type", "text", ""),
            ("trigger.url", "URL", "url", ""),
            ("trigger.host", "Host", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
            ("trigger.response_time_ms", "Response Time (ms)", "number", ""),
            ("trigger.error_message", "Error Message", "text", ""),
            ("trigger.incident_id", "Incident ID", "text", ""),
            ("trigger.started_at", "Started At", "timestamp", ""),
        ),
        "incident.resolved": (
            ("trigger.monitor_id", "Monitor ID", "text", ""),
            ("trigger.monitor_name", "Monitor Name", "text", ""),
            ("trigger.check_type", "Check Type", "text", ""),
            ("trigger.url", "URL", "url", ""),
            ("trigger.host", "Host", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
            ("trigger.response_time_ms", "Response Time (ms)", "number", ""),
            ("trigger.error_message", "Error Message", "text", ""),
            ("trigger.incident_id", "Incident ID", "text", ""),
            ("trigger.resolved_at", "Resolved At", "timestamp", ""),
        ),
        "monitor.created": (
            ("trigger.monitor_id", "Monitor ID", "text", ""),
            ("trigger.monitor_name", "Monitor Name", "text", ""),
            ("trigger.check_type", "Check Type", "text", ""),
            ("trigger.url", "URL", "url", ""),
            ("trigger.host", "Host", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
            ("trigger.response_time_ms", "Response Time (ms)", "number", ""),
            ("trigger.error_message", "Error Message", "text", ""),
        ),
        "monitor.degraded": (
            ("trigger.monitor_id", "Monitor ID", "text", ""),
            ("trigger.monitor_name", "Monitor Name", "text", ""),
            ("trigger.check_type", "Check Type", "text", ""),
            ("trigger.url", "URL", "url", ""),
            ("trigger.host", "Host", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
            ("trigger.response_time_ms", "Response Time (ms)", "number", ""),
            ("trigger.error_message", "Error Message", "text", ""),
            ("trigger.consecutive_failures", "Consecutive Failures", "number", ""),
            ("trigger.status", "Status", "text", ""),
        ),
        "monitor.down": (
            ("trigger.monitor_id", "Monitor ID", "text", ""),
            ("trigger.monitor_name", "Monitor Name", "text", ""),
            ("trigger.check_type", "Check Type", "text", ""),
            ("trigger.url", "URL", "url", ""),
            ("trigger.host", "Host", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
            ("trigger.response_time_ms", "Response Time (ms)", "number", ""),
            ("trigger.error_message", "Error Message", "text", ""),
            ("trigger.status", "Status", "text", ""),
        ),
        "monitor.repeated_failures": (
            ("trigger.monitor_id", "Monitor ID", "text", ""),
            ("trigger.monitor_name", "Monitor Name", "text", ""),
            ("trigger.check_type", "Check Type", "text", ""),
            ("trigger.url", "URL", "url", ""),
            ("trigger.host", "Host", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
            ("trigger.response_time_ms", "Response Time (ms)", "number", ""),
            ("trigger.error_message", "Error Message", "text", ""),
            ("trigger.consecutive_failures", "Consecutive Failures", "number", ""),
            ("trigger.status", "Status", "text", ""),
        ),
        "monitor.ssl_expiring": (
            ("trigger.monitor_id", "Monitor ID", "text", ""),
            ("trigger.monitor_name", "Monitor Name", "text", ""),
            ("trigger.check_type", "Check Type", "text", ""),
            ("trigger.url", "URL", "url", ""),
            ("trigger.host", "Host", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
            ("trigger.response_time_ms", "Response Time (ms)", "number", ""),
            ("trigger.error_message", "Error Message", "text", ""),
            ("trigger.days_until_expiry", "Days Until Expiry", "number", ""),
            ("trigger.ssl_expiry_days", "Ssl Expiry Days", "number", ""),
            ("trigger.ssl_issuer", "Ssl Issuer", "text", ""),
        ),
        "monitor.up": (
            ("trigger.monitor_id", "Monitor ID", "text", ""),
            ("trigger.monitor_name", "Monitor Name", "text", ""),
            ("trigger.check_type", "Check Type", "text", ""),
            ("trigger.url", "URL", "url", ""),
            ("trigger.host", "Host", "text", ""),
            ("trigger.workspace_id", "Workspace ID", "text", ""),
            ("trigger.response_time_ms", "Response Time (ms)", "number", ""),
            ("trigger.error_message", "Error Message", "text", ""),
            ("trigger.status", "Status", "text", ""),
        ),
    },
}


def trigger_fields_for(
    module: str, trigger_type: str | None
) -> tuple[tuple[str, str, str, str], ...]:
    """The fields a given module/trigger pair actually delivers.

    Empty when the pair is unknown — an honest empty list beats inventing paths
    that fail at run time. The picker still accepts a custom
    ``{{trigger.<key>}}`` for anyone working from a payload we have not mapped.
    """
    if module == "crm":
        return _CRM_TRIGGER_FIELDS.get(trigger_type or "", ())
    return _MODULE_TRIGGER_FIELDS.get(module, {}).get(trigger_type or "", ())
