"""Pydantic schemas for API request/response models."""

from gitraki.schemas.developer import (
    DeveloperCreate,
    DeveloperResponse,
    DeveloperUpdate,
    SkillFingerprint,
)
from gitraki.schemas.auth import GitHubAuthResponse, TokenResponse
from gitraki.schemas.career import (
    CareerRoleCreate,
    CareerRoleResponse,
    CareerRoleUpdate,
    RoleRequirements,
    RoleGapAnalysis,
    RoleSuggestion,
    PromotionReadiness,
    LearningPathCreate,
    LearningPathGenerate,
    LearningPathResponse,
    LearningMilestoneResponse,
    PathProgressUpdate,
    StretchAssignment,
    TeamGapAnalysis,
    BusFactorRisk,
    RoadmapSkillAnalysis,
    GeneratedJD,
    InterviewRubric,
    HiringRequirementCreate,
    HiringRequirementResponse,
    CandidateScorecard,
    OrganizationSettingsCreate,
    OrganizationSettingsResponse,
    OrganizationSettingsUpdate,
)

__all__ = [
    "DeveloperCreate",
    "DeveloperResponse",
    "DeveloperUpdate",
    "SkillFingerprint",
    "GitHubAuthResponse",
    "TokenResponse",
    # Career schemas
    "CareerRoleCreate",
    "CareerRoleResponse",
    "CareerRoleUpdate",
    "RoleRequirements",
    "RoleGapAnalysis",
    "RoleSuggestion",
    "PromotionReadiness",
    "LearningPathCreate",
    "LearningPathGenerate",
    "LearningPathResponse",
    "LearningMilestoneResponse",
    "PathProgressUpdate",
    "StretchAssignment",
    "TeamGapAnalysis",
    "BusFactorRisk",
    "RoadmapSkillAnalysis",
    "GeneratedJD",
    "InterviewRubric",
    "HiringRequirementCreate",
    "HiringRequirementResponse",
    "CandidateScorecard",
    "OrganizationSettingsCreate",
    "OrganizationSettingsResponse",
    "OrganizationSettingsUpdate",
]
