#!/usr/bin/env node

/**
 * Rewrite the tool-catalogue table inside docs/mcp.md from the generated MCP
 * manifest, so the prose is hand-written and the table never is.
 *
 * Replaces everything between the BEGIN/END markers; touches nothing else.
 * Runs at prebuild BEFORE generate-docs.mjs, which copies docs/ into
 * public/docs/ — order matters or the published copy lags a build behind.
 *
 *   node scripts/generate-mcp-doc.mjs
 *   node scripts/generate-mcp-doc.mjs --check   # CI: fail if the table is stale
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DOC = path.resolve(ROOT, "..", "docs", "mcp.md");
const MANIFEST = path.join(ROOT, "src", "config", "mcpTools.generated.json");

const BEGIN = "<!-- BEGIN GENERATED TOOLS -->";
const END = "<!-- END GENERATED TOOLS -->";

if (!fs.existsSync(DOC)) {
  console.warn("  docs/mcp.md not found — skipping MCP doc generation");
  process.exit(0);
}

const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));
const esc = (text) => String(text).replace(/\|/g, "\\|").replace(/\n+/g, " ");

const lines = [
  BEGIN,
  "",
  `<!-- Generated by frontend/scripts/generate-mcp-doc.mjs from the backend catalogue (version ${manifest.catalog_version}). Do not edit by hand. -->`,
  "",
  "### Always offered",
  "",
  "| Tool | Description |",
  "| --- | --- |",
];
for (const tool of manifest.generic_tools) {
  lines.push(`| \`${tool.name}\` | ${esc(tool.description)} |`);
}
lines.push("");

if (manifest.workflow_tools.length) {
  lines.push("### Named routines");
  lines.push("");
  lines.push(
    "Offered when the caller holds the capability named. Each binds one operation and takes flat arguments."
  );
  lines.push("");
  lines.push("| Tool | Capability | Description |");
  lines.push("| --- | --- | --- |");
  for (const tool of manifest.workflow_tools) {
    lines.push(
      `| \`${tool.name}\` | \`${tool.capability}\` | ${esc(tool.description.split("\n")[0])} |`
    );
  }
  lines.push("");
}

lines.push("### One tool per capability");
lines.push("");
lines.push(
  "Each takes an `action` (the enum below is the coverage guarantee), plus `path_params`, `query` and `body`."
);
lines.push("");
lines.push("| Tool | Capability | Operations | Writes | Granted by |");
lines.push("| --- | --- | --- | --- | --- |");
for (const c of manifest.categories) {
  const grant = c.app
    ? `the \`${c.app}\` app`
    : `the \`${c.key}\` module on the MCP app${c.privileged ? " (privileged)" : ""}`;
  lines.push(
    `| \`${c.tool.name}\` | \`${c.capability}\` | ${c.operation_count} | ${c.write_count} | ${grant} |`
  );
}
lines.push("");
lines.push(
  `${manifest.total_operations} operations across ${manifest.total_capabilities} capabilities, generated from the backend's OpenAPI schema.`
);
lines.push("");
lines.push(END);

const doc = fs.readFileSync(DOC, "utf8");
const start = doc.indexOf(BEGIN);
const finish = doc.indexOf(END);
if (start === -1 || finish === -1) {
  console.error(`✗ docs/mcp.md is missing the ${BEGIN} / ${END} markers`);
  process.exit(1);
}

const next = doc.slice(0, start) + lines.join("\n") + doc.slice(finish + END.length);

if (process.argv.includes("--check")) {
  if (next !== doc) {
    console.error("✗ docs/mcp.md tool table is stale. Run: npm run mcp:doc");
    process.exit(1);
  }
  console.log(`✓ docs/mcp.md tool table current (${manifest.total_operations} operations)`);
  process.exit(0);
}

if (next !== doc) {
  fs.writeFileSync(DOC, next);
  console.log(`  Regenerated docs/mcp.md tool table (${manifest.total_operations} operations)`);
} else {
  console.log(`  docs/mcp.md tool table already current (${manifest.total_operations} operations)`);
}
